[tool.poetry]
name = "caliagent"
version = "1.0.0"
description = "A workshop covering the calibration of agent-based models."
authors = ["James Bristow <J.Bristow2@massey.ac.nz>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/JBris/calibrating-abms-workshop"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
mesa = "<3.5.1"
pyabc = "^0.13.0"
optuna = "^4.9.0"
mesa-geo = "^0.9.3"
salib = "^1.5.2"
matplotlib = "<=3.11.1"
pandas = "^3.0.5"
scipy = "<1.18.1"
joblib = "^1.5.3"
networkx = "^3.6.1"
iterative-ensemble-smoother = "<1.3.0"
openturns = "^1.27.post1"
scikit-learn = "^1.9.0"
plotly = "^7.0.0"
numba = "^0.67.0"
numpy = "<2.5.2"
elfi = {git = "https://github.com/elfi-dev/elfi.git", rev = "dcbf4c1592a44acc7ff9980c86aeb714a88737f6"}

[tool.poetry.group.torch.dependencies]
torch = { version = "<=2.13.0", source = "pytorch-cpu" }
sbi = "^0.27.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.6.2"
ipython = "^9.17.0"
ipywidgets = "^8.1.9"
jupyter-core = "^5.9.1"
coverage = "^7.15.4"
mypy = "^2.3.1"
types-pyyaml = "^6.0.12.20260815"
ruff = "^0.16.5"
jupyterlab = "^4.6.3"
notebook = "^7.6.2"
jupyterhub = "^5.5.1"
myst-parser = "^5.1.0"
python-discovery = ">=1.6.0"


[tool.poetry.group.docs.dependencies]
sphinx = "<9.1.0"
sphinx-rtd-theme = "^3.1.0"
sphinx-argparse = "^0.6.1"
sphinxcontrib-applehelp = "^2.0.0"
sphinxcontrib-htmlhelp = "^2.1.0"
sphinxcontrib-jsmath = "^1.0.1"
sphinxcontrib-qthelp = "^2.0.0"
sphinxcontrib-serializinghtml = "^2.0.0"
myst-nb = "^1.4.0"
autodoc-pydantic = "^2.2.0"

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py311"
line-length = 90
exclude = [
    "build/",
    "dist/",
    "venv/",
    "docs/source",
]

[tool.ruff.format]
docstring-code-format = true
quote-style = "double"
indent-style = "tab"

[tool.ruff.lint]
extend-select = [
    "UP",
    "F",
    "E",
    "W",
    "I",
    "NPY",
    "RUF"
]

extend-ignore = [
    "W191",
    "E101",
    "RUF012"
]

[tool.ruff.lint.per-file-ignores]
"caliagent/models/wolf_sheep_predation.py" = ["NPY002"]

[tool.codespell]
skip = './docs/build,poetry.lock,docs/**.ipynb'
count = true
quiet-level = 3
ignore-words-list = 'ot,sies,SIES,Te'

[tool.bandit]
skips = ["B101"]
